module.exports = {
  packagerConfig: {
    icon: './public/icon',
    asar: true,
    ignore: [
      '^/\\.vscode($|/)',
      '^/\\.gitignore$',
      '^/\\.next$',
      '^/\\.gitlab$',
      '^/\\.github$',
      '^/\\.yarn$',
      '^/\\.eslintrc.json$',
      '^/\\.prettierrc$',
      '^/\\.yarnrc.yml$',
      '^/\\.gitlab-ci.yml$',
      '^/\\yarn.lock$',
      '^/\\tailwind.config.ts$',
      '^/\\tsconfig.json$',
      '^/\\next.config.js$',
      '^/\\postcss.config.js$',
      '^/forge\\.config\\.js$',
      '^/package-lock\\.json$',
      '^/README\\.md$',
      '^/node_modules/(?!(electron-context-menu|ansi-regex|ansi-styles|astral-regex|cli-truncate|color-convert|color-name|electron-dl|electron-is-dev|emoji-regex|escape-goat|ext-list|ext-name|is-fullwidth-code-point|is-plain-obj|mime-db|modify-filename|path-exists|pupa|slice-ansi|sort-keys-length|sort-keys|string-width|strip-ansi|unused-filename|base64-js|better-sqlite3|bindings|bl|buffer|chownr|decompress-response|deep-extend|detect-libc|end-of-stream|expand-template|file-uri-to-path|fs-constants|github-from-package|ieee754|inherits|ini|lru-cache|mimic-response|minimist|mkdirp-classic|napi-build-utils|node-abi|once|prebuild-install|pump|rc|readable-stream|safe-buffer|semver|simple-concat|simple-get|string_decoder|strip-json-comments|tar-fs|tar-stream|tunnel-agent|util-deprecate|wrappy|yallist|python-shell|@turf|call-bind|commander|concaveman|d3-array|d3-geo|d3-voronoi|deep-equal|define-data-property|define-properties|density-clustering|earcut|es-define-property|es-errors|function-bind|functions-have-names|geojson-equality|geojson-rbush|get-intrinsic|gopd|has-property-descriptors|has-proto|has-symbols|has-tostringtag|hasown|is-arguments|is-date-object|is-regex|object-assign|object-is|object-keys|point-in-polygon|polygon-clipping|quickselect|rbush|regexp.prototype.flags|robust-predicates|set-function-length|set-function-name|skmeans|splaytree|tinyqueue|topojson-client|topojson-server|turf-jsts))',
      '^/dist($|/)',
      '^/Sample map types($|/)',
      '^/DTED-Checking($|/)',
      '^/bkp($|/)',
      '^/src($|/)',
      '^/CHANGELOG$',
      '^/data\\.db$',
      '^/data\\.db-shm$',
      '^/data\\.db-wal$',
      '^/LICENSE$',
      '^/next\\.config\\.js$',
      '^/next-env\\.d\\.ts$',
      '^/tailwind\\.config\\.ts$',
      '^/tsconfig\\.json$',
    ],
    extraResource: ['resources/backend'],
  },
  rebuildConfig: {},
  makers: [
    {
      name: '@electron-forge/maker-squirrel',
      config: {
        name: 'MFPA',
        owners: 'UofG - SH21 Team',
        authors: 'UofG - SH21 Team',
        copyright: 'UofG - SH21 Team',
        exe: 'MFPA.exe',
        icon: './public/icon/icon.ico',
        setupIcon: './public/icon/icon.ico',
      },
    },
    {
      name: '@electron-forge/maker-dmg',
      config: {
        name: 'MFPA',
        owners: 'UofG - SH21 Team',
        authors: 'UofG - SH21 Team',
        copyright: 'UofG - SH21 Team',
        icon: './public/icon/icon.icns',
        setupIcon: './public/icon/icon.icns',
      },
    },
    {
      name: '@electron-forge/maker-deb',
      config: {
        options: {
          name: 'MFPA',
          owners: 'UofG - SH21 Team',
          authors: 'UofG - SH21 Team',
          copyright: 'UofG - SH21 Team',
          icon: './public/icon/icon.png',
          setupIcon: './public/icon/icon.png',
        },
      },
    },
  ],
  plugins: [
    {
      name: '@electron-forge/plugin-auto-unpack-natives',
      config: {},
    },
  ],
  license: 'MIT',
};
